// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hero_protocol.proto

#ifndef PROTOBUF_hero_5fprotocol_2eproto__INCLUDED
#define PROTOBUF_hero_5fprotocol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "common/hero_common.pb.h"
// @@protoc_insertion_point(includes)

namespace protos {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_hero_5fprotocol_2eproto();
void protobuf_AssignDesc_hero_5fprotocol_2eproto();
void protobuf_ShutdownFile_hero_5fprotocol_2eproto();

class HeroListRequest;
class HeroListResponse;
class RequestHeroInfo;
class ChangeArmorRequest;
class ChangeArmorResponse;
class HeroRecruitReq;
class HeroRecruitRes;
class HeroExpRequest;
class HeroEvolReq;
class HeroEvolRes;
class SkillLevelUp;
class DoResult;
class HeroResponse;

// ===================================================================

class HeroListRequest : public ::google::protobuf::Message {
 public:
  HeroListRequest();
  virtual ~HeroListRequest();

  HeroListRequest(const HeroListRequest& from);

  inline HeroListRequest& operator=(const HeroListRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeroListRequest& default_instance();

  void Swap(HeroListRequest* other);

  // implements Message ----------------------------------------------

  HeroListRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeroListRequest& from);
  void MergeFrom(const HeroListRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 mark = 1;
  inline bool has_mark() const;
  inline void clear_mark();
  static const int kMarkFieldNumber = 1;
  inline ::google::protobuf::int32 mark() const;
  inline void set_mark(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protos.HeroListRequest)
 private:
  inline void set_has_mark();
  inline void clear_has_mark();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 mark_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_hero_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_hero_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_hero_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static HeroListRequest* default_instance_;
};
// -------------------------------------------------------------------

class HeroListResponse : public ::google::protobuf::Message {
 public:
  HeroListResponse();
  virtual ~HeroListResponse();

  HeroListResponse(const HeroListResponse& from);

  inline HeroListResponse& operator=(const HeroListResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeroListResponse& default_instance();

  void Swap(HeroListResponse* other);

  // implements Message ----------------------------------------------

  HeroListResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeroListResponse& from);
  void MergeFrom(const HeroListResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .protos.common.Hero heroList = 1;
  inline int herolist_size() const;
  inline void clear_herolist();
  static const int kHeroListFieldNumber = 1;
  inline const ::protos::common::Hero& herolist(int index) const;
  inline ::protos::common::Hero* mutable_herolist(int index);
  inline ::protos::common::Hero* add_herolist();
  inline const ::google::protobuf::RepeatedPtrField< ::protos::common::Hero >&
      herolist() const;
  inline ::google::protobuf::RepeatedPtrField< ::protos::common::Hero >*
      mutable_herolist();

  // optional int32 combat = 2;
  inline bool has_combat() const;
  inline void clear_combat();
  static const int kCombatFieldNumber = 2;
  inline ::google::protobuf::int32 combat() const;
  inline void set_combat(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protos.HeroListResponse)
 private:
  inline void set_has_combat();
  inline void clear_has_combat();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::protos::common::Hero > herolist_;
  ::google::protobuf::int32 combat_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_hero_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_hero_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_hero_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static HeroListResponse* default_instance_;
};
// -------------------------------------------------------------------

class RequestHeroInfo : public ::google::protobuf::Message {
 public:
  RequestHeroInfo();
  virtual ~RequestHeroInfo();

  RequestHeroInfo(const RequestHeroInfo& from);

  inline RequestHeroInfo& operator=(const RequestHeroInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestHeroInfo& default_instance();

  void Swap(RequestHeroInfo* other);

  // implements Message ----------------------------------------------

  RequestHeroInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestHeroInfo& from);
  void MergeFrom(const RequestHeroInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 roleHeroId = 1;
  inline bool has_roleheroid() const;
  inline void clear_roleheroid();
  static const int kRoleHeroIdFieldNumber = 1;
  inline ::google::protobuf::int32 roleheroid() const;
  inline void set_roleheroid(::google::protobuf::int32 value);

  // optional int32 heroId = 2;
  inline bool has_heroid() const;
  inline void clear_heroid();
  static const int kHeroIdFieldNumber = 2;
  inline ::google::protobuf::int32 heroid() const;
  inline void set_heroid(::google::protobuf::int32 value);

  // optional int32 quality = 3;
  inline bool has_quality() const;
  inline void clear_quality();
  static const int kQualityFieldNumber = 3;
  inline ::google::protobuf::int32 quality() const;
  inline void set_quality(::google::protobuf::int32 value);

  // optional int32 roleId = 5;
  inline bool has_roleid() const;
  inline void clear_roleid();
  static const int kRoleIdFieldNumber = 5;
  inline ::google::protobuf::int32 roleid() const;
  inline void set_roleid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protos.RequestHeroInfo)
 private:
  inline void set_has_roleheroid();
  inline void clear_has_roleheroid();
  inline void set_has_heroid();
  inline void clear_has_heroid();
  inline void set_has_quality();
  inline void clear_has_quality();
  inline void set_has_roleid();
  inline void clear_has_roleid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 roleheroid_;
  ::google::protobuf::int32 heroid_;
  ::google::protobuf::int32 quality_;
  ::google::protobuf::int32 roleid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_hero_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_hero_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_hero_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static RequestHeroInfo* default_instance_;
};
// -------------------------------------------------------------------

class ChangeArmorRequest : public ::google::protobuf::Message {
 public:
  ChangeArmorRequest();
  virtual ~ChangeArmorRequest();

  ChangeArmorRequest(const ChangeArmorRequest& from);

  inline ChangeArmorRequest& operator=(const ChangeArmorRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChangeArmorRequest& default_instance();

  void Swap(ChangeArmorRequest* other);

  // implements Message ----------------------------------------------

  ChangeArmorRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChangeArmorRequest& from);
  void MergeFrom(const ChangeArmorRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 roleHeroId = 1;
  inline bool has_roleheroid() const;
  inline void clear_roleheroid();
  static const int kRoleHeroIdFieldNumber = 1;
  inline ::google::protobuf::int32 roleheroid() const;
  inline void set_roleheroid(::google::protobuf::int32 value);

  // required int32 pos = 2;
  inline bool has_pos() const;
  inline void clear_pos();
  static const int kPosFieldNumber = 2;
  inline ::google::protobuf::int32 pos() const;
  inline void set_pos(::google::protobuf::int32 value);

  // required int32 armorId = 3;
  inline bool has_armorid() const;
  inline void clear_armorid();
  static const int kArmorIdFieldNumber = 3;
  inline ::google::protobuf::int32 armorid() const;
  inline void set_armorid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protos.ChangeArmorRequest)
 private:
  inline void set_has_roleheroid();
  inline void clear_has_roleheroid();
  inline void set_has_pos();
  inline void clear_has_pos();
  inline void set_has_armorid();
  inline void clear_has_armorid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 roleheroid_;
  ::google::protobuf::int32 pos_;
  ::google::protobuf::int32 armorid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_hero_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_hero_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_hero_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static ChangeArmorRequest* default_instance_;
};
// -------------------------------------------------------------------

class ChangeArmorResponse : public ::google::protobuf::Message {
 public:
  ChangeArmorResponse();
  virtual ~ChangeArmorResponse();

  ChangeArmorResponse(const ChangeArmorResponse& from);

  inline ChangeArmorResponse& operator=(const ChangeArmorResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChangeArmorResponse& default_instance();

  void Swap(ChangeArmorResponse* other);

  // implements Message ----------------------------------------------

  ChangeArmorResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChangeArmorResponse& from);
  void MergeFrom(const ChangeArmorResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // optional .protos.common.Hero hero = 2;
  inline bool has_hero() const;
  inline void clear_hero();
  static const int kHeroFieldNumber = 2;
  inline const ::protos::common::Hero& hero() const;
  inline ::protos::common::Hero* mutable_hero();
  inline ::protos::common::Hero* release_hero();
  inline void set_allocated_hero(::protos::common::Hero* hero);

  // optional .protos.common.Hero hero2 = 3;
  inline bool has_hero2() const;
  inline void clear_hero2();
  static const int kHero2FieldNumber = 3;
  inline const ::protos::common::Hero& hero2() const;
  inline ::protos::common::Hero* mutable_hero2();
  inline ::protos::common::Hero* release_hero2();
  inline void set_allocated_hero2(::protos::common::Hero* hero2);

  // @@protoc_insertion_point(class_scope:protos.ChangeArmorResponse)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_hero();
  inline void clear_has_hero();
  inline void set_has_hero2();
  inline void clear_has_hero2();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::protos::common::Hero* hero_;
  ::protos::common::Hero* hero2_;
  ::google::protobuf::int32 result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_hero_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_hero_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_hero_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static ChangeArmorResponse* default_instance_;
};
// -------------------------------------------------------------------

class HeroRecruitReq : public ::google::protobuf::Message {
 public:
  HeroRecruitReq();
  virtual ~HeroRecruitReq();

  HeroRecruitReq(const HeroRecruitReq& from);

  inline HeroRecruitReq& operator=(const HeroRecruitReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeroRecruitReq& default_instance();

  void Swap(HeroRecruitReq* other);

  // implements Message ----------------------------------------------

  HeroRecruitReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeroRecruitReq& from);
  void MergeFrom(const HeroRecruitReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 heroId = 1;
  inline bool has_heroid() const;
  inline void clear_heroid();
  static const int kHeroIdFieldNumber = 1;
  inline ::google::protobuf::int32 heroid() const;
  inline void set_heroid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protos.HeroRecruitReq)
 private:
  inline void set_has_heroid();
  inline void clear_has_heroid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 heroid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_hero_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_hero_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_hero_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static HeroRecruitReq* default_instance_;
};
// -------------------------------------------------------------------

class HeroRecruitRes : public ::google::protobuf::Message {
 public:
  HeroRecruitRes();
  virtual ~HeroRecruitRes();

  HeroRecruitRes(const HeroRecruitRes& from);

  inline HeroRecruitRes& operator=(const HeroRecruitRes& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeroRecruitRes& default_instance();

  void Swap(HeroRecruitRes* other);

  // implements Message ----------------------------------------------

  HeroRecruitRes* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeroRecruitRes& from);
  void MergeFrom(const HeroRecruitRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // optional .protos.common.Hero hero = 2;
  inline bool has_hero() const;
  inline void clear_hero();
  static const int kHeroFieldNumber = 2;
  inline const ::protos::common::Hero& hero() const;
  inline ::protos::common::Hero* mutable_hero();
  inline ::protos::common::Hero* release_hero();
  inline void set_allocated_hero(::protos::common::Hero* hero);

  // @@protoc_insertion_point(class_scope:protos.HeroRecruitRes)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_hero();
  inline void clear_has_hero();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::protos::common::Hero* hero_;
  ::google::protobuf::int32 result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_hero_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_hero_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_hero_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static HeroRecruitRes* default_instance_;
};
// -------------------------------------------------------------------

class HeroExpRequest : public ::google::protobuf::Message {
 public:
  HeroExpRequest();
  virtual ~HeroExpRequest();

  HeroExpRequest(const HeroExpRequest& from);

  inline HeroExpRequest& operator=(const HeroExpRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeroExpRequest& default_instance();

  void Swap(HeroExpRequest* other);

  // implements Message ----------------------------------------------

  HeroExpRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeroExpRequest& from);
  void MergeFrom(const HeroExpRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 heroId = 1;
  inline bool has_heroid() const;
  inline void clear_heroid();
  static const int kHeroIdFieldNumber = 1;
  inline ::google::protobuf::int32 heroid() const;
  inline void set_heroid(::google::protobuf::int32 value);

  // required int32 itemId = 2;
  inline bool has_itemid() const;
  inline void clear_itemid();
  static const int kItemIdFieldNumber = 2;
  inline ::google::protobuf::int32 itemid() const;
  inline void set_itemid(::google::protobuf::int32 value);

  // required int32 itemNum = 3;
  inline bool has_itemnum() const;
  inline void clear_itemnum();
  static const int kItemNumFieldNumber = 3;
  inline ::google::protobuf::int32 itemnum() const;
  inline void set_itemnum(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protos.HeroExpRequest)
 private:
  inline void set_has_heroid();
  inline void clear_has_heroid();
  inline void set_has_itemid();
  inline void clear_has_itemid();
  inline void set_has_itemnum();
  inline void clear_has_itemnum();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 heroid_;
  ::google::protobuf::int32 itemid_;
  ::google::protobuf::int32 itemnum_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_hero_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_hero_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_hero_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static HeroExpRequest* default_instance_;
};
// -------------------------------------------------------------------

class HeroEvolReq : public ::google::protobuf::Message {
 public:
  HeroEvolReq();
  virtual ~HeroEvolReq();

  HeroEvolReq(const HeroEvolReq& from);

  inline HeroEvolReq& operator=(const HeroEvolReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeroEvolReq& default_instance();

  void Swap(HeroEvolReq* other);

  // implements Message ----------------------------------------------

  HeroEvolReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeroEvolReq& from);
  void MergeFrom(const HeroEvolReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 heroId = 1;
  inline bool has_heroid() const;
  inline void clear_heroid();
  static const int kHeroIdFieldNumber = 1;
  inline ::google::protobuf::int32 heroid() const;
  inline void set_heroid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protos.HeroEvolReq)
 private:
  inline void set_has_heroid();
  inline void clear_has_heroid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 heroid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_hero_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_hero_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_hero_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static HeroEvolReq* default_instance_;
};
// -------------------------------------------------------------------

class HeroEvolRes : public ::google::protobuf::Message {
 public:
  HeroEvolRes();
  virtual ~HeroEvolRes();

  HeroEvolRes(const HeroEvolRes& from);

  inline HeroEvolRes& operator=(const HeroEvolRes& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeroEvolRes& default_instance();

  void Swap(HeroEvolRes* other);

  // implements Message ----------------------------------------------

  HeroEvolRes* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeroEvolRes& from);
  void MergeFrom(const HeroEvolRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // optional .protos.common.Hero hero = 2;
  inline bool has_hero() const;
  inline void clear_hero();
  static const int kHeroFieldNumber = 2;
  inline const ::protos::common::Hero& hero() const;
  inline ::protos::common::Hero* mutable_hero();
  inline ::protos::common::Hero* release_hero();
  inline void set_allocated_hero(::protos::common::Hero* hero);

  // @@protoc_insertion_point(class_scope:protos.HeroEvolRes)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_hero();
  inline void clear_has_hero();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::protos::common::Hero* hero_;
  ::google::protobuf::int32 result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_hero_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_hero_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_hero_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static HeroEvolRes* default_instance_;
};
// -------------------------------------------------------------------

class SkillLevelUp : public ::google::protobuf::Message {
 public:
  SkillLevelUp();
  virtual ~SkillLevelUp();

  SkillLevelUp(const SkillLevelUp& from);

  inline SkillLevelUp& operator=(const SkillLevelUp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SkillLevelUp& default_instance();

  void Swap(SkillLevelUp* other);

  // implements Message ----------------------------------------------

  SkillLevelUp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SkillLevelUp& from);
  void MergeFrom(const SkillLevelUp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 heroId = 1;
  inline bool has_heroid() const;
  inline void clear_heroid();
  static const int kHeroIdFieldNumber = 1;
  inline ::google::protobuf::int32 heroid() const;
  inline void set_heroid(::google::protobuf::int32 value);

  // required int32 skillId = 2;
  inline bool has_skillid() const;
  inline void clear_skillid();
  static const int kSkillIdFieldNumber = 2;
  inline ::google::protobuf::int32 skillid() const;
  inline void set_skillid(::google::protobuf::int32 value);

  // required int32 itemId = 3;
  inline bool has_itemid() const;
  inline void clear_itemid();
  static const int kItemIdFieldNumber = 3;
  inline ::google::protobuf::int32 itemid() const;
  inline void set_itemid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protos.SkillLevelUp)
 private:
  inline void set_has_heroid();
  inline void clear_has_heroid();
  inline void set_has_skillid();
  inline void clear_has_skillid();
  inline void set_has_itemid();
  inline void clear_has_itemid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 heroid_;
  ::google::protobuf::int32 skillid_;
  ::google::protobuf::int32 itemid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_hero_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_hero_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_hero_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static SkillLevelUp* default_instance_;
};
// -------------------------------------------------------------------

class DoResult : public ::google::protobuf::Message {
 public:
  DoResult();
  virtual ~DoResult();

  DoResult(const DoResult& from);

  inline DoResult& operator=(const DoResult& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DoResult& default_instance();

  void Swap(DoResult* other);

  // implements Message ----------------------------------------------

  DoResult* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DoResult& from);
  void MergeFrom(const DoResult& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protos.DoResult)
 private:
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_hero_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_hero_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_hero_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static DoResult* default_instance_;
};
// -------------------------------------------------------------------

class HeroResponse : public ::google::protobuf::Message {
 public:
  HeroResponse();
  virtual ~HeroResponse();

  HeroResponse(const HeroResponse& from);

  inline HeroResponse& operator=(const HeroResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeroResponse& default_instance();

  void Swap(HeroResponse* other);

  // implements Message ----------------------------------------------

  HeroResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeroResponse& from);
  void MergeFrom(const HeroResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // optional .protos.common.Hero hero = 2;
  inline bool has_hero() const;
  inline void clear_hero();
  static const int kHeroFieldNumber = 2;
  inline const ::protos::common::Hero& hero() const;
  inline ::protos::common::Hero* mutable_hero();
  inline ::protos::common::Hero* release_hero();
  inline void set_allocated_hero(::protos::common::Hero* hero);

  // optional bool skillLvUp = 3;
  inline bool has_skilllvup() const;
  inline void clear_skilllvup();
  static const int kSkillLvUpFieldNumber = 3;
  inline bool skilllvup() const;
  inline void set_skilllvup(bool value);

  // @@protoc_insertion_point(class_scope:protos.HeroResponse)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_hero();
  inline void clear_has_hero();
  inline void set_has_skilllvup();
  inline void clear_has_skilllvup();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::protos::common::Hero* hero_;
  ::google::protobuf::int32 result_;
  bool skilllvup_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_hero_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_hero_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_hero_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static HeroResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// HeroListRequest

// optional int32 mark = 1;
inline bool HeroListRequest::has_mark() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HeroListRequest::set_has_mark() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HeroListRequest::clear_has_mark() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HeroListRequest::clear_mark() {
  mark_ = 0;
  clear_has_mark();
}
inline ::google::protobuf::int32 HeroListRequest::mark() const {
  return mark_;
}
inline void HeroListRequest::set_mark(::google::protobuf::int32 value) {
  set_has_mark();
  mark_ = value;
}

// -------------------------------------------------------------------

// HeroListResponse

// repeated .protos.common.Hero heroList = 1;
inline int HeroListResponse::herolist_size() const {
  return herolist_.size();
}
inline void HeroListResponse::clear_herolist() {
  herolist_.Clear();
}
inline const ::protos::common::Hero& HeroListResponse::herolist(int index) const {
  return herolist_.Get(index);
}
inline ::protos::common::Hero* HeroListResponse::mutable_herolist(int index) {
  return herolist_.Mutable(index);
}
inline ::protos::common::Hero* HeroListResponse::add_herolist() {
  return herolist_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::protos::common::Hero >&
HeroListResponse::herolist() const {
  return herolist_;
}
inline ::google::protobuf::RepeatedPtrField< ::protos::common::Hero >*
HeroListResponse::mutable_herolist() {
  return &herolist_;
}

// optional int32 combat = 2;
inline bool HeroListResponse::has_combat() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HeroListResponse::set_has_combat() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HeroListResponse::clear_has_combat() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HeroListResponse::clear_combat() {
  combat_ = 0;
  clear_has_combat();
}
inline ::google::protobuf::int32 HeroListResponse::combat() const {
  return combat_;
}
inline void HeroListResponse::set_combat(::google::protobuf::int32 value) {
  set_has_combat();
  combat_ = value;
}

// -------------------------------------------------------------------

// RequestHeroInfo

// optional int32 roleHeroId = 1;
inline bool RequestHeroInfo::has_roleheroid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestHeroInfo::set_has_roleheroid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestHeroInfo::clear_has_roleheroid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestHeroInfo::clear_roleheroid() {
  roleheroid_ = 0;
  clear_has_roleheroid();
}
inline ::google::protobuf::int32 RequestHeroInfo::roleheroid() const {
  return roleheroid_;
}
inline void RequestHeroInfo::set_roleheroid(::google::protobuf::int32 value) {
  set_has_roleheroid();
  roleheroid_ = value;
}

// optional int32 heroId = 2;
inline bool RequestHeroInfo::has_heroid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RequestHeroInfo::set_has_heroid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RequestHeroInfo::clear_has_heroid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RequestHeroInfo::clear_heroid() {
  heroid_ = 0;
  clear_has_heroid();
}
inline ::google::protobuf::int32 RequestHeroInfo::heroid() const {
  return heroid_;
}
inline void RequestHeroInfo::set_heroid(::google::protobuf::int32 value) {
  set_has_heroid();
  heroid_ = value;
}

// optional int32 quality = 3;
inline bool RequestHeroInfo::has_quality() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RequestHeroInfo::set_has_quality() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RequestHeroInfo::clear_has_quality() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RequestHeroInfo::clear_quality() {
  quality_ = 0;
  clear_has_quality();
}
inline ::google::protobuf::int32 RequestHeroInfo::quality() const {
  return quality_;
}
inline void RequestHeroInfo::set_quality(::google::protobuf::int32 value) {
  set_has_quality();
  quality_ = value;
}

// optional int32 roleId = 5;
inline bool RequestHeroInfo::has_roleid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RequestHeroInfo::set_has_roleid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RequestHeroInfo::clear_has_roleid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RequestHeroInfo::clear_roleid() {
  roleid_ = 0;
  clear_has_roleid();
}
inline ::google::protobuf::int32 RequestHeroInfo::roleid() const {
  return roleid_;
}
inline void RequestHeroInfo::set_roleid(::google::protobuf::int32 value) {
  set_has_roleid();
  roleid_ = value;
}

// -------------------------------------------------------------------

// ChangeArmorRequest

// required int32 roleHeroId = 1;
inline bool ChangeArmorRequest::has_roleheroid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChangeArmorRequest::set_has_roleheroid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChangeArmorRequest::clear_has_roleheroid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChangeArmorRequest::clear_roleheroid() {
  roleheroid_ = 0;
  clear_has_roleheroid();
}
inline ::google::protobuf::int32 ChangeArmorRequest::roleheroid() const {
  return roleheroid_;
}
inline void ChangeArmorRequest::set_roleheroid(::google::protobuf::int32 value) {
  set_has_roleheroid();
  roleheroid_ = value;
}

// required int32 pos = 2;
inline bool ChangeArmorRequest::has_pos() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChangeArmorRequest::set_has_pos() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChangeArmorRequest::clear_has_pos() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChangeArmorRequest::clear_pos() {
  pos_ = 0;
  clear_has_pos();
}
inline ::google::protobuf::int32 ChangeArmorRequest::pos() const {
  return pos_;
}
inline void ChangeArmorRequest::set_pos(::google::protobuf::int32 value) {
  set_has_pos();
  pos_ = value;
}

// required int32 armorId = 3;
inline bool ChangeArmorRequest::has_armorid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ChangeArmorRequest::set_has_armorid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ChangeArmorRequest::clear_has_armorid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ChangeArmorRequest::clear_armorid() {
  armorid_ = 0;
  clear_has_armorid();
}
inline ::google::protobuf::int32 ChangeArmorRequest::armorid() const {
  return armorid_;
}
inline void ChangeArmorRequest::set_armorid(::google::protobuf::int32 value) {
  set_has_armorid();
  armorid_ = value;
}

// -------------------------------------------------------------------

// ChangeArmorResponse

// required int32 result = 1;
inline bool ChangeArmorResponse::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChangeArmorResponse::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChangeArmorResponse::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChangeArmorResponse::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 ChangeArmorResponse::result() const {
  return result_;
}
inline void ChangeArmorResponse::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// optional .protos.common.Hero hero = 2;
inline bool ChangeArmorResponse::has_hero() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChangeArmorResponse::set_has_hero() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChangeArmorResponse::clear_has_hero() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChangeArmorResponse::clear_hero() {
  if (hero_ != NULL) hero_->::protos::common::Hero::Clear();
  clear_has_hero();
}
inline const ::protos::common::Hero& ChangeArmorResponse::hero() const {
  return hero_ != NULL ? *hero_ : *default_instance_->hero_;
}
inline ::protos::common::Hero* ChangeArmorResponse::mutable_hero() {
  set_has_hero();
  if (hero_ == NULL) hero_ = new ::protos::common::Hero;
  return hero_;
}
inline ::protos::common::Hero* ChangeArmorResponse::release_hero() {
  clear_has_hero();
  ::protos::common::Hero* temp = hero_;
  hero_ = NULL;
  return temp;
}
inline void ChangeArmorResponse::set_allocated_hero(::protos::common::Hero* hero) {
  delete hero_;
  hero_ = hero;
  if (hero) {
    set_has_hero();
  } else {
    clear_has_hero();
  }
}

// optional .protos.common.Hero hero2 = 3;
inline bool ChangeArmorResponse::has_hero2() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ChangeArmorResponse::set_has_hero2() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ChangeArmorResponse::clear_has_hero2() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ChangeArmorResponse::clear_hero2() {
  if (hero2_ != NULL) hero2_->::protos::common::Hero::Clear();
  clear_has_hero2();
}
inline const ::protos::common::Hero& ChangeArmorResponse::hero2() const {
  return hero2_ != NULL ? *hero2_ : *default_instance_->hero2_;
}
inline ::protos::common::Hero* ChangeArmorResponse::mutable_hero2() {
  set_has_hero2();
  if (hero2_ == NULL) hero2_ = new ::protos::common::Hero;
  return hero2_;
}
inline ::protos::common::Hero* ChangeArmorResponse::release_hero2() {
  clear_has_hero2();
  ::protos::common::Hero* temp = hero2_;
  hero2_ = NULL;
  return temp;
}
inline void ChangeArmorResponse::set_allocated_hero2(::protos::common::Hero* hero2) {
  delete hero2_;
  hero2_ = hero2;
  if (hero2) {
    set_has_hero2();
  } else {
    clear_has_hero2();
  }
}

// -------------------------------------------------------------------

// HeroRecruitReq

// required int32 heroId = 1;
inline bool HeroRecruitReq::has_heroid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HeroRecruitReq::set_has_heroid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HeroRecruitReq::clear_has_heroid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HeroRecruitReq::clear_heroid() {
  heroid_ = 0;
  clear_has_heroid();
}
inline ::google::protobuf::int32 HeroRecruitReq::heroid() const {
  return heroid_;
}
inline void HeroRecruitReq::set_heroid(::google::protobuf::int32 value) {
  set_has_heroid();
  heroid_ = value;
}

// -------------------------------------------------------------------

// HeroRecruitRes

// required int32 result = 1;
inline bool HeroRecruitRes::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HeroRecruitRes::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HeroRecruitRes::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HeroRecruitRes::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 HeroRecruitRes::result() const {
  return result_;
}
inline void HeroRecruitRes::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// optional .protos.common.Hero hero = 2;
inline bool HeroRecruitRes::has_hero() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HeroRecruitRes::set_has_hero() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HeroRecruitRes::clear_has_hero() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HeroRecruitRes::clear_hero() {
  if (hero_ != NULL) hero_->::protos::common::Hero::Clear();
  clear_has_hero();
}
inline const ::protos::common::Hero& HeroRecruitRes::hero() const {
  return hero_ != NULL ? *hero_ : *default_instance_->hero_;
}
inline ::protos::common::Hero* HeroRecruitRes::mutable_hero() {
  set_has_hero();
  if (hero_ == NULL) hero_ = new ::protos::common::Hero;
  return hero_;
}
inline ::protos::common::Hero* HeroRecruitRes::release_hero() {
  clear_has_hero();
  ::protos::common::Hero* temp = hero_;
  hero_ = NULL;
  return temp;
}
inline void HeroRecruitRes::set_allocated_hero(::protos::common::Hero* hero) {
  delete hero_;
  hero_ = hero;
  if (hero) {
    set_has_hero();
  } else {
    clear_has_hero();
  }
}

// -------------------------------------------------------------------

// HeroExpRequest

// required int32 heroId = 1;
inline bool HeroExpRequest::has_heroid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HeroExpRequest::set_has_heroid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HeroExpRequest::clear_has_heroid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HeroExpRequest::clear_heroid() {
  heroid_ = 0;
  clear_has_heroid();
}
inline ::google::protobuf::int32 HeroExpRequest::heroid() const {
  return heroid_;
}
inline void HeroExpRequest::set_heroid(::google::protobuf::int32 value) {
  set_has_heroid();
  heroid_ = value;
}

// required int32 itemId = 2;
inline bool HeroExpRequest::has_itemid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HeroExpRequest::set_has_itemid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HeroExpRequest::clear_has_itemid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HeroExpRequest::clear_itemid() {
  itemid_ = 0;
  clear_has_itemid();
}
inline ::google::protobuf::int32 HeroExpRequest::itemid() const {
  return itemid_;
}
inline void HeroExpRequest::set_itemid(::google::protobuf::int32 value) {
  set_has_itemid();
  itemid_ = value;
}

// required int32 itemNum = 3;
inline bool HeroExpRequest::has_itemnum() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HeroExpRequest::set_has_itemnum() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HeroExpRequest::clear_has_itemnum() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HeroExpRequest::clear_itemnum() {
  itemnum_ = 0;
  clear_has_itemnum();
}
inline ::google::protobuf::int32 HeroExpRequest::itemnum() const {
  return itemnum_;
}
inline void HeroExpRequest::set_itemnum(::google::protobuf::int32 value) {
  set_has_itemnum();
  itemnum_ = value;
}

// -------------------------------------------------------------------

// HeroEvolReq

// required int32 heroId = 1;
inline bool HeroEvolReq::has_heroid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HeroEvolReq::set_has_heroid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HeroEvolReq::clear_has_heroid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HeroEvolReq::clear_heroid() {
  heroid_ = 0;
  clear_has_heroid();
}
inline ::google::protobuf::int32 HeroEvolReq::heroid() const {
  return heroid_;
}
inline void HeroEvolReq::set_heroid(::google::protobuf::int32 value) {
  set_has_heroid();
  heroid_ = value;
}

// -------------------------------------------------------------------

// HeroEvolRes

// required int32 result = 1;
inline bool HeroEvolRes::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HeroEvolRes::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HeroEvolRes::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HeroEvolRes::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 HeroEvolRes::result() const {
  return result_;
}
inline void HeroEvolRes::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// optional .protos.common.Hero hero = 2;
inline bool HeroEvolRes::has_hero() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HeroEvolRes::set_has_hero() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HeroEvolRes::clear_has_hero() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HeroEvolRes::clear_hero() {
  if (hero_ != NULL) hero_->::protos::common::Hero::Clear();
  clear_has_hero();
}
inline const ::protos::common::Hero& HeroEvolRes::hero() const {
  return hero_ != NULL ? *hero_ : *default_instance_->hero_;
}
inline ::protos::common::Hero* HeroEvolRes::mutable_hero() {
  set_has_hero();
  if (hero_ == NULL) hero_ = new ::protos::common::Hero;
  return hero_;
}
inline ::protos::common::Hero* HeroEvolRes::release_hero() {
  clear_has_hero();
  ::protos::common::Hero* temp = hero_;
  hero_ = NULL;
  return temp;
}
inline void HeroEvolRes::set_allocated_hero(::protos::common::Hero* hero) {
  delete hero_;
  hero_ = hero;
  if (hero) {
    set_has_hero();
  } else {
    clear_has_hero();
  }
}

// -------------------------------------------------------------------

// SkillLevelUp

// required int32 heroId = 1;
inline bool SkillLevelUp::has_heroid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SkillLevelUp::set_has_heroid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SkillLevelUp::clear_has_heroid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SkillLevelUp::clear_heroid() {
  heroid_ = 0;
  clear_has_heroid();
}
inline ::google::protobuf::int32 SkillLevelUp::heroid() const {
  return heroid_;
}
inline void SkillLevelUp::set_heroid(::google::protobuf::int32 value) {
  set_has_heroid();
  heroid_ = value;
}

// required int32 skillId = 2;
inline bool SkillLevelUp::has_skillid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SkillLevelUp::set_has_skillid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SkillLevelUp::clear_has_skillid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SkillLevelUp::clear_skillid() {
  skillid_ = 0;
  clear_has_skillid();
}
inline ::google::protobuf::int32 SkillLevelUp::skillid() const {
  return skillid_;
}
inline void SkillLevelUp::set_skillid(::google::protobuf::int32 value) {
  set_has_skillid();
  skillid_ = value;
}

// required int32 itemId = 3;
inline bool SkillLevelUp::has_itemid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SkillLevelUp::set_has_itemid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SkillLevelUp::clear_has_itemid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SkillLevelUp::clear_itemid() {
  itemid_ = 0;
  clear_has_itemid();
}
inline ::google::protobuf::int32 SkillLevelUp::itemid() const {
  return itemid_;
}
inline void SkillLevelUp::set_itemid(::google::protobuf::int32 value) {
  set_has_itemid();
  itemid_ = value;
}

// -------------------------------------------------------------------

// DoResult

// required int32 result = 1;
inline bool DoResult::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DoResult::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DoResult::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DoResult::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 DoResult::result() const {
  return result_;
}
inline void DoResult::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// -------------------------------------------------------------------

// HeroResponse

// required int32 result = 1;
inline bool HeroResponse::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HeroResponse::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HeroResponse::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HeroResponse::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 HeroResponse::result() const {
  return result_;
}
inline void HeroResponse::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// optional .protos.common.Hero hero = 2;
inline bool HeroResponse::has_hero() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HeroResponse::set_has_hero() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HeroResponse::clear_has_hero() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HeroResponse::clear_hero() {
  if (hero_ != NULL) hero_->::protos::common::Hero::Clear();
  clear_has_hero();
}
inline const ::protos::common::Hero& HeroResponse::hero() const {
  return hero_ != NULL ? *hero_ : *default_instance_->hero_;
}
inline ::protos::common::Hero* HeroResponse::mutable_hero() {
  set_has_hero();
  if (hero_ == NULL) hero_ = new ::protos::common::Hero;
  return hero_;
}
inline ::protos::common::Hero* HeroResponse::release_hero() {
  clear_has_hero();
  ::protos::common::Hero* temp = hero_;
  hero_ = NULL;
  return temp;
}
inline void HeroResponse::set_allocated_hero(::protos::common::Hero* hero) {
  delete hero_;
  hero_ = hero;
  if (hero) {
    set_has_hero();
  } else {
    clear_has_hero();
  }
}

// optional bool skillLvUp = 3;
inline bool HeroResponse::has_skilllvup() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HeroResponse::set_has_skilllvup() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HeroResponse::clear_has_skilllvup() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HeroResponse::clear_skilllvup() {
  skilllvup_ = false;
  clear_has_skilllvup();
}
inline bool HeroResponse::skilllvup() const {
  return skilllvup_;
}
inline void HeroResponse::set_skilllvup(bool value) {
  set_has_skilllvup();
  skilllvup_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protos

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_hero_5fprotocol_2eproto__INCLUDED
